#+TITLE: Oniro's Blueprints
#+AUTHOR: P.Coval + A.Gherzan #FOSDEM2022
#+EMAIL: philippe.coval@huawei.com andrei.gherzan@huawei.com
#+OPTIONS: num:nil timestamp:nil toc:nil tags:nil tag:nil ^:nil
#+REVEAL_DEFAULT_FRAG_STYLE: appear
#+REVEAL_DEFAULT_SLIDE_BACKGROUND: https://oniroproject.org/images/shapes.png
#+REVEAL_DEFAULT_SLIDE_BACKGROUND_OPACITY: 0.15
#+REVEAL_EXTRA_CSS: ../oniro-template/local.css
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Presentations slides">
#+REVEAL_HLEVEL: 3
#+REVEAL_INIT_OPTIONS: transition:'zoom'
#+REVEAL_PLUGINS: (highlight)
#+REVEAL_ROOT: https://cdn.jsdelivr.net/gh/hakimel/reveal.js@4.1.0/
#+REVEAL_SLIDE_FOOTER:
#+REVEAL_SLIDE_HEADER:
#+REVEAL_THEME: night
#+REVEAL_PLUGINS: (highlight)
#+MACRO: tags-on-export (eval (format "%s" (cond ((org-export-derived-backend-p org-export-current-backend 'md) "#+OPTIONS: tags:1") ((org-export-derived-backend-p org-export-current-backend 'reveal) "#+OPTIONS: tags:nil num:nil reveal_single_file:t"))))

#+begin_export html
<!--
SPDX-License-Identifier: CC-BY-4.0
SPDX-License-URL: https://spdx.org/licenses/CC-BY-4.0.html
SPDX-FileCopyrightText: Huawei Inc.
-->
#+end_export

#+ATTR_HTML: :width 10% :align right
https://docs.oniroproject.org/en/latest/_static/ONIRO.svg

#+BEGIN_NOTES

Context:
https://gitlab.eclipse.org/eclipse-wg/oniro-wg/proposal-incubation-stage-oniro/proposal-incubation-oniro-marketing/-/merge_requests/22

Sources:
https://booting.oniroproject.org/rzr/oniro-presentations/-/tree/sandbox/pcoval/main/docs/oniro-blueprints

Preview:
https://www.volatile.rzr.cloudns.org/docs/oniro-blueprints/

## Abstract

https://fosdem.org/2022/schedule/event/oniro_blueprints/

## Track

Embedded, Mobile and Automotive devroom

https://fosdem.org/2022/schedule/track/embedded_mobile_and_automotive/#

Sunday 2022-02-06
Start time: 13:30-14:00

## Title

From Oniro Blueprints for IoT devices

## Subtitle

Open-source seeds to products.

## Abstract

In the Eclipse Oniro project, a distributed OS for consumer electronics,
we're proposing a collection of "blueprints" use cases and their implementations
using embedded software on reference hardware.

Today, we are going to explain our motivations for the blueprints' approach
and of course how to replicate and deploy firmware from sources and
why Oniro can be flexible to create the device of your dream.

## Description

Oniro is an ambitious Eclipse project,
one of its challenges is to defragment existing IoT ecosystems.

To target a bigger heterogeneous range of IoT devices,
openness, flexibility, and interoperability,
should be enabled at the Operating System level.

Since the beginning of this versatile OS development,
a complementary blueprint concept was introduced
to be more aligned with different aspects of the software and hardware industry.

Blueprints are standalone projects that are addressing specific uses cases
by providing "semi final integration" that would make use of the underneath technology.

Those minimal viable products are not only used for demonstration or validation purposes,
but they can serve as a base to create production-ready solutions.
Blueprints also could inspire devices makers to address similar or more sophisticated use cases.

Today as we speak, our reference blueprints include
a vending machine, an IoT gateway, a door lock, keypad and more.

The results of our work are going to be demonstrated and we will be presenting
what is common and what differs.

Each of those achievements are targeting different uses case and different environments,
but many steps can be factorized from building process, customization to
security or IP compliance scanning.

Expect to see demos on how our Oniro project leverages other opensource projects
like Yocto/OE Embedded distribution, Linux and Zephyr Kernel, LVGL UI toolkit,
OpenThread mesh networking, Web of Things and more.

Oniro: The Distributed Operating System That Connects Consumer Devices Big and Small
https://oniroproject.org/

Oniro sources
https://booting.oniroproject.org/

Oniro Videos
https://www.youtube.com/watch?v=p-gSvehb-As&list=PLy7t4z5SYNaQBDReZmeHAknEchYmu0LLa#OniroPlaylist


# META #

URL: https://cryptpad.fr/code/#/2/code/edit/gsskOoKFko73ngDMV9MMUb8j/#OniroBlueprints

https://gitlab.eclipse.org/eclipse-wg/oniro-wg/proposal-incubation-stage-oniro/proposal-incubation-oniro-marketing/-/merge_requests/21

https://chat.ostc-eu.org/ostc/pl/i3noi75iaf8jz8hsanzyj1nuuh#FosdemBlueprints

# TODO ##

- Please check: TODO/@bero TODO/@andrei, TODO/@*
- Feedback welcome (add TODO for comments at end of each slides)
- once draft is stable rzr will sync contents to:
  - https://booting.oniroproject.org/rzr/oniro-presentations

#+END_NOTES

* Agenda                                                                 :1m:
  #+ATTR_REVEAL: :frag (fade-in)
  - Who is talking?
  - Introduction: Oniro Project
  - Blueprints in the Oniro Context
  - Showcases/demos
  - Getting started with Oniro
  - Conclusion
  - Q&A

* Presentation                                                           :1m:
  #+ATTR_REVEAL: :frag (fade-in)
  - We're a part of:
    - [[https://projects.eclipse.org/projects/oniro/][Eclipse Oniro]] project
    - [[https://www.ostc-eu.org/][Huawei OpenSource Techology Center]]
  - Philippe Coval
    - Senior Technical Marketing
  - Andrei Gherzan
    - Principal Solution Architect
  - It's a teamwork:
    - Thx @bero, @sudhesh, @stefan, @pidge, Seco's @fabio...
* What's Oniro Project?                                                  :2m:
  #+ATTR_REVEAL: :frag (fade-in)
  - An open source distributed operating system
    - Targeting IoT devices
  - Defragment development for embedded sys:
    - Avoid technology silos
    - Unified tooling, common policies

* Who is hosting Oniro?                                                  :1m:
  :PROPERTIES:
  :reveal_background: https://www.eclipse.org/org/artwork/images/eclipse_foundation_logo_wo.png
  :reveal_background_opacity: 0.07
  :END:
   #+ATTR_REVEAL: :frag (fade-in)
  - An [[https://projects.eclipse.org/projects/oniro][Eclipse Foundation]] top level project
    - supported by an EF working group
  - Designed to be [[https://gitee.com/openharmony][OpenHarmony]] compatible
    - project hosted @ [[https://www.openatom.org/][OpenAtom]] Foundation

* What's Oniro Platform?                                                 :2m:
  #+ATTR_REVEAL: :frag (fade-in)
  - Standard software base
    - for making products and solutions
  - Based on mature open source projects
    - Reuse what's best on the "OSS market"
    - Fill gaps
  - Multiple kernels (CPU, MCU) supported
    - Linux, Zephyr, LiteOS...
  - Common build tooling ([[http://www.openembedded.org/wiki][bitbake]] OE/Yocto)
  - Point of convergence
    - For product-based projects
   
* Oniro provides                                                         :1m:
  #+ATTR_REVEAL: :frag (fade-in)
  - Defines and implements best practices:
    #+ATTR_REVEAL: :frag (fade-in)
    - Open development community
      - CI/CD, Testing
    - Legal:
      - IP Compliance
    - Security, Privacy
    - OTA Updates...
  - Blueprint projects
  
* Blueprints' projects                                                   :2m:
  #+ATTR_REVEAL: :frag (fade-in)
  - Minimum Viable Products:
    - Design and implementation
    - Fully opensource
  - Final integration
    - Feature validation and testing
  - Maintenance with reproducibility in mind
    
* Blueprints' use cases                                                  :1m:
  #+ATTR_REVEAL: :frag (fade-in)
  - Product foundations based on use-cases:
    - Vending machine, Key Pad
    - Door lock
    - IoT gateway
  - Your use-case, your product.

#+BEGIN_NOTES
Each use-case/demo section should have the following structure:
- Use-case/blueprint introduction
- Demo/Pictures/etc
- Documentation for follow up and test driving
#+END_NOTES

#+BEGIN_NOTES
 Oniro's Linux flavour
  - Using mainline kernel
  - Based on Yocto dunfell
    - Core distro (derivate of poky)
    - Support: seco-intel, raspberrypi (+BSPs)
    - Oniro layers
  - Plus meta-blueprints
#+END_NOTES
* Oniro's Vending machine                                                :2m:
  :PROPERTIES:
  :reveal_background: https://cdn.fosstodon.org/media_attachments/files/107/269/294/404/602/312/original/67b165042b685e6b.jpeg
  :reveal_background_opacity: 0.07
  :END:

  @@html:<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/HQ9hD63ypvI?rel=0&start=556#VendingMachine" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>@@

  #+BEGIN_NOTES
  TODO: announce (rewatch):  Day: Sunday ; Start: 10:00
  https://fosdem.org/2022/schedule/event/lvgl/
  Script:
  - It's using Linux kernel and LVGL toolkit
    - (originally made for MCU but then ported to wayland)
    - I upstreamed recipe in OE
  - Communication between controller app is using WS
    - API is inspired by webthings (simplified W3C WebOfThings)
   #+END_NOTES

* Oniro's Keypad                                                         :1m:
  :PROPERTIES:
  :reveal_background: https://files.mastodon.social/media_attachments/files/107/603/519/184/782/270/original/5ad14fc987d4bcd9.jpeg
  :reveal_background_opacity: 0.9
  :END:

  #+BEGIN_NOTES
  TODO: Short demo video , may be better on v8
  Script:
  - If we like to move the VM display app to MC
    - in theory : we could rebase on different kernel (zephyr) but versions are not yet aligned
    - so wrote an other app for keypad blueprint
      - this app is connected using BLE
      - any volunteer to write bridge to vm's controller app?
  #+END_NOTES

* Door lock                                                              :2m:
  :PROPERTIES:
  :reveal_background: https://cdn.fosstodon.org/media_attachments/files/107/269/293/686/781/360/original/ed4a9adcf222caa4.jpeg
  :reveal_background_opacity: .5
  :END:
  @@html:<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/x3HeJO7Atis?rel=0&start=283#OniroDoorLock" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>@@
 
  #+BEGIN_NOTES
  TODO: announce (rewatch) fosdem talk: Saturday Start: 17:30
  https://fosdem.org/2022/schedule/event/gpio_linux_vs_zaphyr/
  https://docs.oniroproject.org/projects/blueprints/en/latest/doorlock.html

  TODO/@bero: tell us what you want to be said or just play your words
  
  Picture [would prefer a short demo video even if it's just the solenoid opening and closing - doesn't need to use more time than the picture, but with something moving, it'll look better]
  Animated gif would do the trick , inline video seems ok, we can skip it anytime
  #+END_NOTES

* IoT Gateway                                                            :1m:
  :PROPERTIES:
  :reveal_background: https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/FOSDEM_logo.svg/2034px-FOSDEM_logo.svg.png
  :reveal_background_opacity: .1
  :END:
  #+ATTR_REVEAL: :frag (fade-in)
  #+BEGIN_rightcol
  #+ATTR_HTML: :width 35% :align right
  https://docs.oniroproject.org/projects/blueprints/en/latest/_images/gateway-commissioner-3.jpg
  #+END_rightcol
  #+BEGIN_leftcol
  #+ATTR_HTML: :width 45% :align left
  https://docs.oniroproject.org/projects/blueprints/en/latest/_images/gateway-hw-setup.png
  #+END_leftcol
  
#+BEGIN_NOTES
Announce: Day: Sunday Start: 15:00

- https://fosdem.org/2022/schedule/event/openthread_mesh_network/

TODO/@stephan:  tell us what you want to be said

- The Thread protocol specifies a low-power IoT mesh network.
- It offers self-healing, low latency and IPv6 connectivity without a single point of failure
- this BP demonstrate a Linux based OpenThread border router and Zephyr based mesh node  -

TODO: make short video clip and comment over it (unsure we will have time),
since it's accepted it's better to g

#+END_NOTES

* Getting started                                                        :1m:
  #+ATTR_REVEAL: :frag (fade-in)
  - Refer to reference documentation:
    - https://docs.oniroproject.org/
  - Download Oniro's sources:
    @@html:<pre>repo init -u https://booting.oniroproject.org/distro/oniro</pre>@@
  - Add blueprints collection:
    @@html:<pre>git clone https://booting.oniroproject.org/distro/meta-oniro-blueprints</pre>@@
  - Get inspired to add your $custom blueprint along
     - matching the kernel ($flavour) of choice

* Build custom blueprint                                                 :1m:
  #+ATTR_REVEAL: :frag (fade-in)
  - Use blueprint's distro configuration:
    @@html:<pre>export DISTRO="oniro-$flavour-$custom"</pre>@@
  - Build image to be deployed to device
    @@html:<pre>bitbake blueprint-$custom-image # for Linux based BP</pre>@@
    @@html:<pre>bitbake zephyr-blueprint-$custom # for Zephyr based BP</pre>@@

#+BEGIN_NOTES
It would be nice to align names, is issue reported ?
#+END_NOTES
  
* Summary                                                                :1m:
  #+ATTR_REVEAL: :frag (fade-in)
  - Oniro is multi-kernel OS for embedded/IoT:
    - Based on Linux or Zephyr or LiteOS...
  - It includes "Blueprints" projects:
    - To satisfy business requirements
    - Easy to reproduce from scratch
  - Try existing blueprints or create
    - Your own Oniro-based demo or product!
  - Visit [[https://fosdem.org/2022/schedule/event/welcome_oniro/][FOSDEM Oniro Stand]] for more!

* Resources and more:                                                 :QA:5m:
  - https://OniroProject.org/
    - https://docs.OniroProject.org/
    - https://docs.oniroproject.org/projects/blueprints/
    - https://booting.OniroProject.org/
  - https://eclipse.org/
  - https://yoctoproject.org/
  - https://zephyrproject.org/

* + Extras ?                                                          :extra:
  - [[https://www.youtube.com/playlist?list=PLy7t4z5SYNaQBDReZmeHAknEchYmu0LLa][Oniro playlist]]
  - [[https://forum.ostc-eu.org/t/openharmony-at-fosdem-21/180][Fosdem 2021]]
  - [[https://www.eclipsecon.org/2021][EclipseCon 2021]]
  - [[https://www.sfscon.it/programs/2021/#][SFSCON2021]]

* Howto: IoT Gateway                                                  :extra:

  @@html:<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/o_3ITbSAvNg#OniroIotGateway" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>@@

* Howto: Doorlock                                                     :extra:

  @@html:<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/x3HeJO7Atis?rel=0&t=0#OniroDoorLock" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>@@
 
* Howto: Vending machine                                              :extra:

  @@html:<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/HQ9hD63ypvI?rel=0&t=0#VendingMachine" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>@@

* Oniro's Zephyr flavour                                              :extra:
  - Use mainline zephyr kernel
    - Upstream's Zephyr use west
  - Oniro uses bitbake (like on Linux)
    - Uses meta-zephyr + meta-zephyr-bsp    

* Build Keypad                                                        :extra:
  - repo init -u https://booting.oniroproject.org/distro/oniro
  - git clone https://booting.oniroproject.org/distro/meta-oniro-blueprints
  - TEMPLATECONF=../oniro/flavours/zephyr . ./oe-core/oe-init-build-env build-oniro-zephyr
  - export MACHINE=nrf52840dk-nrf52840
  - bitbake zephyr-blueprint-keypad

  
#+BEGIN_NOTES
TODO/@andrei: Add smart panel video 
even if it was created before oniro
#+END_NOTES

* Video Playback                                                      :extra:
  @@html:<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/p-gSvehb-As?rel=0#OniroWelcome" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>@@

  #+BEGIN_NOTES
  TODO: update once published at:
  https://fosdem.org/2022/archives/
  #+END_NOTES

#  LocalWords:  defragment reproducibility
